# Generated by Django 4.1.6 on 2023-03-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_order_alter_skill_image_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
